main_path: /data1/erez/Documents/diff2
sub_dir_tstsave: 0_tests
load_file: ema_0.9999_800000.pt #model000175.pt #ema_0.9999_000175.pt
#model_path: /data1/erez/Documents/diff2/211218_193412_unconditioned_generation_cont10k_with_val/model430000.pt
#resume_ema_opt: False
train_phase: False

#MODEL_FLAGS
image_size: 128
num_channels: 64 # 128
num_res_blocks: 2
learn_sigma: True # True
class_cond: True # True for clip embd adaGN
#attention_resolutions: 16,problem # D:16,8, REC: 32,16,8
num_heads: 1 # D:4
use_fp16: True # D:False
noise_schedule: cosine #linear
# DATA
data_dir: /data2/erez/datasets/faces/raw_data/thumbnails128x128/ # train
clip_file_path: /data2/erez/datasets/faces/raw_data/clip_thumbnails128x128_ViT-B32_dict.pt

data_dir_test: /data2/erez/datasets/faces/raw_data/celeba_hq_256/
clip_file_path_test: /data2/erez/datasets/faces/raw_data/clip_embd_celeba_hq_256_ViT-B32_dict.pt
# num_workers: 4

# val-test params:
batch_size: 4
num_samples: 4
denoise_start_point: -1 # steps from x to 0, 800
timestep_respacing: 1000

#classifier:
clip_guidance_lambda: 1
l1_lambda: 100

#model_path: p