main_path: /data1/erez/Documents/diff_raw
# load: '' # use -f argument
# sub_dir_tstsave: 0_tests # NU
load_file: ema_0.9999_400000.pt # or use --lf ; file name to load from folder given by (-f/ argument
#load_file: model050000.pt # or use --lf ; file name to load from folder given by (-f/ argument
#model_path: /data1/erez/Documents/diff2/211218_193412_unconditioned_generation_cont10k_with_val/model430000.pt
#resume_ema_opt: False
format_strs: log,csv,wandb
job_type: evaluation
wandb_tags: []

#MODEL_FLAGS
image_size: 128
input_channels: 4
num_channels: 64 # 128
num_res_blocks: 2
# learn_sigma: False # True
model_var_type_name: fixed_large  # learned_sigma / fixed_small / fixed_large (default)
model_mean_type_name: xstart
class_cond: False # True for clip embd adaGN
#attention_resolutions: 16,problem # D:16,8, REC: 32,16,8
num_heads: 1 # D:4
use_fp16: True # D:False
noise_schedule: cosine #linear
# DATA
data_dir_test: /data2/erez/datasets/faces/raw_data/celeba_hq_256/
clip_file_path_test: /data2/erez/datasets/faces/raw_data/clip_embd_celeba_hq_256_ViT-B32_dict.pt
# num_workers: 4

# val-test params:
batch_size: 1
num_samples: 8

# DIFFUSION_FLAGS
diffusion_type: noise_diffusion # base_diffusion / coldmix / noise_diffusion
diffusion_start_point: -1 # steps from x to 0, 800 ; set -1 for full diffusion (T to 0)
diffusion_steps: 1000
#timestep_respacing: 100 # (respace for inference using less times)


#model_path: p
# CUDA_VISIBLE_DEVICES=1 python scripts/image_sample.py --config_file configs/noisediff_sample_config.yaml -d sample65k